* Child Games

This will be a set of six interactive games for roughly pre-school age
children.

** Games
- Tic-Tac-Toe
- Bubble Pop
- Matching
- Dressing the Character
- How Many?
- Face-Torso-Legs

* Site Design

** Site map
Pretty flat layout without nesting.  Small children need a simple
navigation structure.  All of the games can be accessed from any of
the other pages.  The menu page can be used for entering the player's
name and/or other information (age/gender).

- Menu page (index.html)
- Tic Tac Toe (tic-tac-toe.html)
- Bubble Pop (bubble-pop.html)
- Matching (matching.html)
- Dressing the Character (dressing.html)
- How Many? (how-many.html)
- Face-Torso-Legs (face-torso-legs.html)

** Technical requirements

*** Rendering
Still not sure if I should use HTML5 canvas or if I should make the
games in straight HTML5+CSS for rendering, or a combination of both.
I should judge by performance of common browsers.

- See http://diveintohtml5.info/canvas.html
- See http://blog.teamtreehouse.com/brief-introduction-svg

*** Responsive
I'm not sure how much the site needs reformat to fit different screen
sizes.  The main difference, I would think, will be how large the
navigation icons will be.  On desktop/laptop screen sizes, I would
want to use that extra horizontal space somehow, so with larger,
animated, and more interactive graphics.  On mobile devices a
different method should be used.

*** Audio?
I know I'll need animations and a highly interactive interface, but
I'll leave it an open question whether I should incorporate audio.

*** Saving
I'll need a method for saving the state of the game.  For instance,
when the player puts different clothes on one of the characters, it
would be nice if this change is reflected on the rest of the
site. Should I use cookies or what exactly is HTML5 storage?

- See http://diveintohtml5.info/storage.html
- See http://blog.teamtreehouse.com/html5-local-storage

* Characters

** TODO Draw characters
The characters need to be drawn from different angles and with
different expressions for animation purposes. Needs to look good both
small, icon-size, and close-up.

- [ ] Elephant of the savannah
- [ ] Penguin of the artic
- [ ] Rabbit of the woods
- [ ] Whale of the ocean
- [ ] Lizard of the desert
- [ ] Goat of the mountains

* Games

** Tic Tac Toe
Play "Tic Tac Toe" with characters instead of X's and O's

** Bubble Pop
Popping large and small bubbles on the screen

** Matching
Matching items/cha different expressions for animation purposes. Click
on one item, and then click another item to match it.

** Dressing the Character
Show a large image of a character, and then offer the player clothes
to put on him/her. 
- Would be neat if the clothes that the player chooses is seen on the
  rest of the games.

** How Many
Have the player choose the correct number for the number of objects
being displayed

** Face-Torso-Legs
Have the player choose different combinations of the upper, middle,
and lower bodies of the characters.
